[uwsgi]
uid = searxng
gid = searxng

workers = %k
threads = 4

chmod-socket = 666

single-interpreter = true
master = true
lazy-apps = true
enable-threads = 4

module = searx.webapp

pythonpath = /usr/local/searxng/
chdir = /usr/local/searxng/searx/

disable-logging = true
log-5xx = true
